services:
  dbt-warehouse:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbt_user
      POSTGRES_PASSWORD: dbt_password
      POSTGRES_DB: data_warehouse
    volumes:
      - ./dw_volume:/var/lib/postgresql/data

